spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    locale: zh_CN
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/static/
    locale: zh_CN

platform:
  security:
    permit-all:
      ## home
      - /
      ## favicon
      - /favicon.ico
      ## static resources
      - /static/**
      ## captcha
      - /captcha
      - /captcha/behavior
  captcha:
    path-matches: ## format {id}[?] [method:]path
      - login? POST:/login