spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    locale: zh-CN
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xx?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/static/
    locale: zh-CN


platform:
  security:
    permit-all:
      ## home
      - /
      ## static resources
      - /static/**
      ## captcha
      - /captcha
      - /captcha/behavior
      - GET:/sys/settings
  captcha:
    path-matches: ## format {id}[?] [method:]path
      - login? POST:/login
mybatis:
  configuration:
    map-underscore-to-camel-case: true