spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    locale: zh-CN
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xx?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/static/
    locale: zh-CN
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true


platform:
  oss:
    enabled: false
    provider: aliyun
    ## aliyun的endpont, qiniu的bucket domain
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    access-key:
    secret-key:
    bucket:
  storage:
    enabled: true
    provider: filesystem
    base-location: F:/storage
    base-uri: http://localhost/storage/
    dev-server: true
  security:
    permit-all:
      ## home
      - /
      ## static resources
      - /static/**
      ## captcha
      - /captcha
      - /captcha/behavior
      - GET:/sys/settings
  captcha:
    path-matches: ## format {id}[?] [method:]path
      - login? POST:/login